### PR TITLE
Added codecarbon feature

### PR DESCRIPTION
**Pull request by Sharjeeliv**
This is the codeCarbon feature implemented, it was tested to work before recent updates. Unfortunately, after the most recent sync from the base repo, the pipeline is not working.

### CODE REVIEW

**Review by Sharjeeliv — COMMENTED** [review]
Removed extra files, added carbon emission tracking for main pipeline.

**Comment by hosseinfani** [comment]
@Sharjeeliv 
Not sure I see the required changes. Can we have a quick meeting sometime tomorrow so you can explain?

**Comment by Sharjeeliv** [comment]
I tried the github.dev to make the changes, but it seems that it left the comment without committing. I was trying to multi-delete using git to avoid a lot of commit messages, but if I can not figure it out I will manually delete each file/folder. I can meet tomorrow between 9 am - 2 pm to give an update.

**Comment by hosseinfani** [comment]
@Sharjeeliv 
Thanks. See you at 9am tomorrow.

**Comment by Sharjeeliv** [comment]
Just to clarify will this be online or in person?

**Comment by hosseinfani** [comment]
online pls

**Comment by Sharjeeliv** [comment]
I think everything should be done now:
- Changes from the meeting implemented
- Only essential files are pushed
- Pipeline is functional for gensim
- Mallet is not working yet but from some online reading it seems to be a setup issue on mac rather than the code

**Comment by Sharjeeliv** [comment]
Manually merged by Soroush

**Pull request closed without merging**
